[GLOBAL]
pants_version = "2.6.1"
print_stacktrace = true
dynamic_ui = true
pantsd = true
colors = true

backend_packages.add = [
    "pants.backend.python",
    "pants.backend.python.typecheck.mypy"
]

build_patterns = ["BUILD.pants"]

[anonymous-telemetry]
enabled = false

[source]
marker_filenames = ["BUILD.pants"]

[python-setup]
interpreter_constraints = ["CPython>=3.6.6,<3.8"]

[python-infer]
imports = false

[pex]
bootstrap_interpreter_names = ["python3.7"]
